DROP DATABASE IF EXISTS RENTARIG;
CREATE DATABASE RENTARIG;
USE RENTARIG;

DROP TABLE IF EXISTS address;
CREATE TABLE ADDRESS(

ADDRESS_ID INT AUTO_INCREMENT NOT NULL,
LINE_1 VARCHAR(255) NOT NULL,
LINE_2 VARCHAR(255) NOT NULL,
STATE VARCHAR(2) NOT NULL,
ZIP INT NOT NULL,
PRIMARY KEY(ADDRESS_ID)

);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
 
	USERNAME VARCHAR(30) NOT NULL,

    FIRST_NAME VARCHAR(30) NOT NULL,

    LAST_NAME VARCHAR(30) NOT NULL,

    SHIPPING_ADDRESS INT NOT NULL REFERENCES ADDRESS(ADDRESS_ID),

    BILLING_ADDRESS INT NOT NULL REFERENCES ADDRESS(ADDRESS_ID),

    EMAIL VARCHAR(255) NOT NULL,

    PHONE_NUMBER VARCHAR(255) NOT NULL,

    PRIMARY KEY(USERNAME)

    );
    
    DROP TABLE IF EXISTS products;
CREATE TABLE PRODUCTS(

   PRODUCT_ID INT NOT NULL AUTO_INCREMENT,

   PRODUCT_NAME VARCHAR(255) NOT NULL,

   SHORT_DESC  TEXT NOT NULL,

   LONG_DESC MEDIUMTEXT NOT NULL,

   STOCK INT NOT NULL,

   PRIMARY KEY (PRODUCT_ID)

);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(

    ORDER_ID INT NOT NULL,

    USER_ID VARCHAR(30) NOT NULL REFERENCES USER(USERNAME),

    ORDER_DATE DATETIME NOT NULL,

    PRIMARY KEY(ORDER_ID)

    );
    
    DROP TABLE IF EXISTS ITEMS;
    CREATE TABLE ITEMS (
ITEM_ID INT NOT NULL AUTO_INCREMENT,
ORDER_ID INT NOT NULL REFERENCES ORDERS(ORDER_ID),
PRODUCT_ID INT NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
QUANTITY INT NOT NULL,
PRIMARY KEY(ITEM_ID)
);
    